version: '3.1'
services:
  api:
    container_name: 'Board-Game-Tracker'
    build: ../board-game-tracker
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    container_name: 'Board-Game-Tracker-DB'
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BGT
      POSTGRES_USER: BGT_ADMIN
    volumes:
      - type: volume
        source: api-postgres-volume
        target: /var/lib/postgresql/data
    ports:
      - "6666:5432"
    restart: always
volumes:
  api-postgres-volume: